name       : stella
version    : 4.7.3
release    : 1
source     :
    - https://github.com/stella-emu/stella/releases/download/release-4.7.3/stella-4.7.3-src.tar.xz : 93a75d1b343b1e66b6dc526c0f9d8a0c3678d346033f7cdfe76dc93f14d956ad
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : games.emulator
summary    : Stella Atari 2600 Emulator
description: |
    Stella is a multi-platform Atari 2600 VCS emulator.
builddeps  :
    - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
