name       : stella
version    : 6.0.1
release    : 7
source     :
    - https://github.com/stella-emu/stella/releases/download/6.0.1/stella-6.0.1-src.tar.xz : d611f98bb35ed9eacfb63826b12b4e8b67b874a2a87019d4bdaf1e7f4724c40d
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
component  : games.emulator
summary    : Stella Atari 2600 Emulator
description: |
    Stella is a multi-platform Atari 2600 VCS emulator.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
