name       : stella
version    : 5.1
release    : 2
source     :
    - https://github.com/stella-emu/stella/releases/download/5.1/stella-5.1-src.tar.xz : 96a5ed7aa27f29e6af3643bf4af08e0441d46c1b3f47f0d0c55fa6f0e41f407b
license    :
    - GPL-2.0
    - BSD-3-Clause
component  : games.emulator
summary    : Stella Atari 2600 Emulator
description: |
    Stella is a multi-platform Atari 2600 VCS emulator.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

