name       : stella
version    : '6.0'
release    : 4
source     :
    - https://github.com/stella-emu/stella/releases/download/6.0/stella-6.0-src.tar.xz : 17aa8c5f08e09c51dd7dd933f93b0a1929d2832bd66f3bd994fa50ebb2b9a2b1
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
component  : games.emulator
summary    : Stella Atari 2600 Emulator
description: |
    Stella is a multi-platform Atari 2600 VCS emulator.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
