name       : stella
version    : 5.1.1
release    : 3
source     :
    - https://github.com/stella-emu/stella/releases/download/5.1.1/stella-5.1.1-src.tar.xz : 3de6ad86e4e881d1a23395c36c5453eb8a1160d0f3a021992fe990a009a933da
license    :
    - GPL-2.0-or-later
    - BSD-3-Clause
component  : games.emulator
summary    : Stella Atari 2600 Emulator
description: |
    Stella is a multi-platform Atari 2600 VCS emulator.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
