name       : stella
version    : 6.1.2
release    : 10
source     :
    - https://github.com/stella-emu/stella/releases/download/6.1.2/stella-6.1.2-src.tar.xz : 8086e57c231625f0b840ca361f493969247d20476cbb53609d778d37bda17c34
homepage   : https://stella-emu.github.io/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
component  : games.emulator
summary    : Stella Atari 2600 Emulator
description: |
    Stella is a multi-platform Atari 2600 VCS emulator.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(sdl2)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
